# Inputs for the threexui-panel module.
#
# Two groups: (1) how to reach + authenticate to ONE 3x-ui panel, (2) the desired
# inbounds + clients to declare on it. The module configures its own provider from the
# connection inputs (Terraform cannot for_each a provider, so one module instance == one
# panel; live/<panel>/ wires each instance — the documented multi-server pattern).

# --- Connection / auth (one panel) ---

variable "endpoint" {
  description = "Base URL of the 3x-ui panel, e.g. http://localhost:2053. The panel is ClusterIP-only, so this is reached through an SSH tunnel (VPN off) or kubectl port-forward (VPN on)."
  type        = string
}

variable "base_path" {
  description = "Panel webBasePath (the obscured panel path). Secret-in-disguise — sourced from SOPS, not hard-coded."
  type        = string
  default     = "/"
}

variable "username" {
  description = "Panel admin username (steady-state / desired)."
  type        = string
}

variable "password" {
  description = "Panel admin password (steady-state / desired). When manage_panel_user is true, the panel is rotated to this; it's applied write-only, so it is NOT stored in state."
  type        = string
  sensitive   = true
}

variable "insecure_skip_verify" {
  description = "Skip TLS verification (true when the panel uses a self-signed cert; over a localhost tunnel the endpoint is plain HTTP, so usually false)."
  type        = bool
  default     = false
}

# --- Panel admin user management (optional credential rotation) ---

variable "manage_panel_user" {
  description = "Manage the panel admin user via threexui_panel_user — rotate it to username/password. The new password is applied write-only (not persisted in state)."
  type        = bool
  default     = true
}

variable "bootstrap_username" {
  description = "Initial/old panel username for first-run rotation (e.g. \"admin\"). Set together with bootstrap_password. On 3x-ui v3 it is tried only if the steady-state username/password is rejected — so it can stay set harmlessly after rotation."
  type        = string
  default     = null
}

variable "bootstrap_password" {
  description = "Initial/old panel password for first-run rotation (e.g. \"admin\"). Set together with bootstrap_username."
  type        = string
  default     = null
  sensitive   = true
}

variable "panel_password_version" {
  description = "Bump this to force re-sending the panel password (write-only passwords need a version to re-apply). Increment when you change the password."
  type        = number
  default     = 1
}

# --- Subscription server ---
#
# null → leave the panel's subscription settings untouched. When set, the module enables
# the sub server and generates a RANDOM URL path (obscurity, like webBasePath — it lives in
# state, not Git). `public_url` is the Gateway-fronted base (scheme://host:port, no trailing
# path); generated subscription links use `<public_url>/<random-path>/<sub_id>`.

variable "subscription" {
  description = "Subscription server settings (null = untouched)."
  type = object({
    public_url  = string # e.g. https://sub.vps.ger.ips.sanch.pet:8443
    enabled     = optional(bool, true)
    port        = optional(number, 2096)
    json_enable = optional(bool, true)
    title       = optional(string)

    # URI path. Leave `path` null to GENERATE a random one (obscurity; lives in state, not
    # Git). The path_* knobs are passed straight to random_string — expose them so an
    # EXISTING 3x-ui path can be imported without a forced replacement: `terraform import`
    # sets random_string's char-class flags to the provider defaults (all true), so to make
    # the import a no-op set the knobs to match (e.g. path_upper = true for a mixed-case path).
    # Set `path` explicitly to adopt a literal path and skip generation entirely.
    path         = optional(string)
    path_length  = optional(number, 16)
    path_special = optional(bool, false)
    path_upper   = optional(bool, false)
    path_lower   = optional(bool, true)
    path_numeric = optional(bool, true)
  })
  default = null
}

# --- Desired state: inbounds ---
#
# VLESS + Reality focused (the homelab's actual workload). Reality keypair and short_ids
# are auto-generated by the panel when left null — do NOT hard-code them in Git; they are
# secrets that live in the (encrypted) state. Extend this object for more protocols later.

variable "inbounds" {
  description = "VLESS-Reality inbounds to declare, keyed by a stable local name."
  type = map(object({
    port                 = number
    remark               = string
    enable               = optional(bool, true)
    reality_target       = string                 # SNI dest, e.g. \"www.amazon.com:443\"
    reality_server_names = list(string)           # e.g. [\"www.amazon.com\"]
    reality_private_key  = optional(string)       # null => panel auto-generates
    reality_short_ids    = optional(list(string)) # null => panel auto-generates
  }))
  default = {}
}

# --- Desired state: clients ---
#
# Each client references an inbound by its key in var.inbounds. UUID (client_id) and
# sub_id auto-generate when null; pin sub_id to preserve subscription links across rebuilds.

variable "clients" {
  description = "Clients to declare, keyed by a stable local name."
  type = map(object({
    inbound_key = string # key into var.inbounds
    email       = string # unique per panel
    flow        = optional(string, "xtls-rprx-vision")
    enable      = optional(bool, true)
    total_gb    = optional(number, 0) # 0 = unlimited
    expiry_time = optional(number, 0) # unix ms, 0 = no expiry
    limit_ip    = optional(number, 0) # 0 = no limit
    comment     = optional(string)
    tg_id       = optional(number)
    sub_id      = optional(string) # null => auto-generate
  }))
  default = {}

  validation {
    condition     = alltrue([for c in values(var.clients) : contains(keys(var.inbounds), c.inbound_key)])
    error_message = "Every client.inbound_key must match a key in var.inbounds."
  }
}
