apiVersion: v1
kind: Secret
metadata:
    name: anylink-secret
    namespace: vpn
stringData:
    LINK_JWT_SECRET: ENC[AES256_GCM,data:9warI6Lh87vAoCINjU3KWIj4aamTw0QKuSVatrnRcIG55G1FOKNAjqMNTsTtdNf10NZAr6ILj7vshkC2zYlnWQ==,iv:PxUg90lMSBe3+g/8ha48fcui4zn/oiKnqRz2yIli7LQ=,tag:J4yjDK8MshYSjHJKDwW94w==,type:str]
    LINK_ADMIN_PASS: ENC[AES256_GCM,data:/jvBkfkbSBRGQw2YW7pm0duKFyUtlb9r9ujLXUghvoXX/RJiJhguYJLDIDZgqobstCKSp939vD/9/8Q4,iv:8AiNNB+IqUtKefqFwe+JO8e0Uj3EC7kyMm78ofF6Pco=,tag:jnInoeJJ5AVY48yTIxyHTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0QwZXMwVU1LOFpjUFRV
            M1J2b3NoRnJDb0Jmam5wQzVuYjd1T1cxRVZnCmRFTTVsZmJGZGJ6QVlsYk5NZ2Fo
            R3pJRlNYSzNKeVF0dnJBR3VSYnMvRDAKLS0tIG9jU0w5QS8zZUxpUHhnUTZubTFH
            RUNGZnh4S0E0V1RJNzE1ZmVuNW1mczAK4eWSOJaIW+Erg2Y8I7VbBD2NXE4RHCzB
            cd7Bm4pRSUX/gV4zy1bqz9QTchIKEdC/4Zrjwd2Ka405NT4cmOW2fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ayd37q6cyqrh2d2jgz04jx0guxmj483d0tchhqd6sd83ukcf4vusm4p63q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T01:31:37Z"
    mac: ENC[AES256_GCM,data:8PEO/COGOmwfnfNvCkj6O4/EXi3/cvqUcEHGQx+vq0WxAxcyC9IClRxS1+tr1g+nDzWJcGFwPI50xfv5J3IT5MEp34hGpcKivfNvHePYwOSR69scNhTFc/TC2tB2k/VFjDIUUMNYSIPiBQez30M9QX7piX8nBOH/MQQ6o3iTGy0=,iv:qijmTw7NvZ35h/yxUToV1X9bLXbe+MwPIxubMIpqP54=,tag:wm5XrkPfIFQvyVinZV8F8w==,type:str]
    version: 3.13.1
