apiVersion: v1
kind: Secret
metadata:
    name: anylink-secret
    namespace: vpn
stringData:
    LINK_JWT_SECRET: ENC[AES256_GCM,data:9warI6Lh87vAoCINjU3KWIj4aamTw0QKuSVatrnRcIG55G1FOKNAjqMNTsTtdNf10NZAr6ILj7vshkC2zYlnWQ==,iv:PxUg90lMSBe3+g/8ha48fcui4zn/oiKnqRz2yIli7LQ=,tag:J4yjDK8MshYSjHJKDwW94w==,type:str]
    LINK_ADMIN_PASS: ENC[AES256_GCM,data:PzRq0k8yMKkggD22XFoZo2ZhCl8pitUvUyHTfxHwmkE36BKx7nsc9GZki+ZckdoPgz1lLVvC6Iixtm9qZVLh1WEntg==,iv:esMBT+TxKux8yPQ0zdR/pbYiqCMrQBx5QmBFwjYqE4k=,tag:yN2Ap4lZBUhT63vmjj2D1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0QwZXMwVU1LOFpjUFRV
            M1J2b3NoRnJDb0Jmam5wQzVuYjd1T1cxRVZnCmRFTTVsZmJGZGJ6QVlsYk5NZ2Fo
            R3pJRlNYSzNKeVF0dnJBR3VSYnMvRDAKLS0tIG9jU0w5QS8zZUxpUHhnUTZubTFH
            RUNGZnh4S0E0V1RJNzE1ZmVuNW1mczAK4eWSOJaIW+Erg2Y8I7VbBD2NXE4RHCzB
            cd7Bm4pRSUX/gV4zy1bqz9QTchIKEdC/4Zrjwd2Ka405NT4cmOW2fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ayd37q6cyqrh2d2jgz04jx0guxmj483d0tchhqd6sd83ukcf4vusm4p63q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T01:20:42Z"
    mac: ENC[AES256_GCM,data:ZtCG8MNiesWgs7JPFlztsjJ/9rBqr+dHAI7E2XgxDGOoZi+hfBfLjnyQI5ixsg+htJvgIjw+kiDjOemY+F3Z28LZe6u7lh0a8tXmnc0ZIQ2z2zkytrQ9ef5CW2HyFa8LLA3l7GwOT6mILkFKTzYLR62cNzcQUkRRp4DdbahB3fU=,iv:f/QH82LIYc11B6Vp5v/CcDfdsJQ95+VFGWdimQAuuac=,tag:PcKAxjhRrfPngi/h8WPCvQ==,type:str]
    version: 3.13.1
