apiVersion: v1
kind: Secret
metadata:
    name: anylink-secret
    namespace: vpn
stringData:
    LINK_JWT_SECRET: ENC[AES256_GCM,data:9warI6Lh87vAoCINjU3KWIj4aamTw0QKuSVatrnRcIG55G1FOKNAjqMNTsTtdNf10NZAr6ILj7vshkC2zYlnWQ==,iv:PxUg90lMSBe3+g/8ha48fcui4zn/oiKnqRz2yIli7LQ=,tag:J4yjDK8MshYSjHJKDwW94w==,type:str]
    LINK_ADMIN_PASS: ENC[AES256_GCM,data:HJVFh7TojrArZddiwtVtpr0uSe0QBiLq,iv:SsROyh0VtKlp0AIG9aEcAqc0mvZtuUlvj3TAyc4lEU0=,tag:UzDPhmtP9PByK38a/kNTgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0QwZXMwVU1LOFpjUFRV
            M1J2b3NoRnJDb0Jmam5wQzVuYjd1T1cxRVZnCmRFTTVsZmJGZGJ6QVlsYk5NZ2Fo
            R3pJRlNYSzNKeVF0dnJBR3VSYnMvRDAKLS0tIG9jU0w5QS8zZUxpUHhnUTZubTFH
            RUNGZnh4S0E0V1RJNzE1ZmVuNW1mczAK4eWSOJaIW+Erg2Y8I7VbBD2NXE4RHCzB
            cd7Bm4pRSUX/gV4zy1bqz9QTchIKEdC/4Zrjwd2Ka405NT4cmOW2fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ayd37q6cyqrh2d2jgz04jx0guxmj483d0tchhqd6sd83ukcf4vusm4p63q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T00:10:00Z"
    mac: ENC[AES256_GCM,data:/hwNETsjr+7dYMLV8FB/o1Mvejb3evf//8AlWlhJOUkQcBQfbxFwavZJHt/JInX8WirgGYcobYH0+uih5K/7pF8x8bH/vy0xSXOkrlSTd76W9IAp86t6J+ub1EAPH7G9eTH/QQBaqrsWFkREQZI9bz9Y1w9aR6EWCyQNZolIfFs=,iv:1Q6EaQLd0mA6srFQDEH0Wwsa4MqXYt0v+xnm9fKAaE4=,tag:znkd0kPNHb4m7//NUdmyjg==,type:str]
    version: 3.13.1
