---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/gateway-api
  - ../base/cert-manager
  - ../base/nginx-gateway-fabric
  - ../base/reloader
  - gateway.yaml
  - certificate.yaml
components:
  - ../components/letsencrypt
