---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anylink-tls
  namespace: vpn
spec:
  secretName: anylink-tls
  dnsNames:
    - anylink.vps-2.usa.ips.sanch.pet
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
