apiVersion: v1
kind: Secret
metadata:
    name: anylink-secret
    namespace: vpn
type: Opaque
stringData:
    LINK_JWT_SECRET: ENC[AES256_GCM,data:TAaOz4/8ERHs0W1BV66pV1URbxD4VdggoiRgjqKYTUnbP+HkOqo+mnBnwLI=,iv:PhkUAwMef77xwQhXnY3yoIiRIesJmyGpsDt/oRcymaM=,tag:IBmXIjHxdaAovLXW5RGOIw==,type:str]
    #ENC[AES256_GCM,data:AOLc5GlwFlmf0Fv2z3E+sH6FHtr35/Kjmcjd5YB1uV3hShJReI0/EzT3roRvjThHF5w+f0OYTmk5vY9zQg==,iv:7b8O0vtMS6AoygIg04VKxMZ699WzSlKw2lUIFycrQbs=,tag:0fSFtK4nWPtvE3HtFigy0w==,type:comment]
    #ENC[AES256_GCM,data:mEstumHffQSpEeMdk8gn4bI0z7gHNz4oyq78Ea7c9cN8CI2lhnfFjKYmFzh6cjSFOz+xApd91rW0Fp8zntWZuyXnMDyJ0PwR2A==,iv:CW5s6YH3akuzdInujPe6PLcxlnKpOH8CxYWsCZ4Ljyg=,tag:tGnnenZ4/5/KEnHD1fJQqA==,type:comment]
    #ENC[AES256_GCM,data:aNGoEFAx5Tn4NFQ8uHsfFEmxZSxtHgKwxsTjcoA/Thj3SJvwY0alJHRRwOKDdA==,iv:ojKWyJ2nh7VzbjZMjlGlXs1v07bJieKBMIuGRj0yj5g=,tag:JDqUktwVl/TQDqYTOEFa4Q==,type:comment]
    LINK_ADMIN_PASS: ENC[AES256_GCM,data:64aZe/TgvBaMI13E+/RH6t9+Q0NbVk/f,iv:RlHcXZdLQC5ed0YkCGW0Xm6YnOBPem+sZ6P9RzMqLl8=,tag:FFGw7ivu/IpsSM6yweZyEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZGpuVGhSQ0RSRmo0Vllk
            RHZ4aVBCSnJ2SzVMY1g4UFlJMGoxODE5WERFCi91eHVZVjFKL0xnL0hpQnhOWXIv
            VHZ0Y3B2bThWYXg5RStvV3ZZNW81MVUKLS0tIGVlL2NwRHRoeXVpS3RtZVdCWXFU
            RWp3VUZNWE5pN2ZjTlVKSzFLd2VuK00KEgAkJ7xw7hE1SuLXGIYqwdg/AMvPUJH6
            8AxcJcXEHrDfJKs8IPqRohPTWFinuNAppB+IHw/aNQMzDGvwA45fMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ayd37q6cyqrh2d2jgz04jx0guxmj483d0tchhqd6sd83ukcf4vusm4p63q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T09:22:32Z"
    mac: ENC[AES256_GCM,data:XSDfZHbxWZ0qM2wDu/wv+e1K9bzK1eow7/jl0SoVC+M7bZVxNXh/eJ87IU8lbDE5bli30qVHuT9IzBoV8Smal1AXUM6xhDkYSUMF3IcDaj8oRuHogyxpfUcGMEjz7HQWViVr+rQa3oLjTWARngY1L2f+a8JRZ3AZejJIq25Smy8=,iv:LNCUq76qWZs8A9ZSXBSmRlUXzdgsjKQ8FB8mWZzb8Cw=,tag:djkjv/dlb4euBfbiHT/+Og==,type:str]
    version: 3.13.1
