apiVersion: v1
kind: Secret
metadata:
    name: gost-config
    namespace: vpn
type: Opaque
stringData:
    gost.yml: ENC[AES256_GCM,data:C1BQmaqkyEG/3D1wDlOGiBqnr+LIsJFS+1G67qRv7uOcPRcsMLUVWHfX8L4x2vzy1iJm4ixBee/dbmAVRGK14nuWE2udsHvWDEgeWnLVQISprsr2z50DiltUD6vwtzN0cTYH4XG5hNK//rhwnH1ChZd0jyRjeajiHKgLoZTN5ddJZoLkymZ2Wd+i1d4NQQR0veVHb2bmDlluUj63xcQXQDe9NXlk3gWwqVZkmKqktbUbA0AWTUdVg5Bp+u+oS7NkcUjTBfXf42LP0UJTxnXetJ5PJeUPKYpE8vjsM4JYL2+Sc7sS8TXbJQhBJIPwI5YFtRnfdWxaUTm0wGxuhqFh1RZwZ8EamGaBu7xJTT1TWjPw1bRwy0si71mcMFM4z3hXv0jT1MpIZQ/rfgW+9xwj3bsfqM93UN5MU/zETjVstBIWPhoiW3HJbW3r5c9owOq4FM7yWOg063kiVCgu5mynKP+1hvpNEXKoIDq7PvFWsQc/W4TodLvBBIVqxgsZ8XeuTv40+LcUyDjg4ZcJTiPBtE60B/rmpJQ0Qee1WqaXs9tGvRTMTfovt8gvrO8o/1rgFijQjI0t6yAl3tIZiLBxovnt/HRlVUrU7oghc6jF0a1K/V+xIQJIshBPAB3GNj7qOKVnOjccgv/JvnWTlgYW7SxGMPsSpFBOLg5mcw==,iv:A/rKgx9T9brMeKJKAjQyzVPhxxE0mhzU23rYUsNO17I=,tag:6ri09lEr8zUcxBC3gXMoQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbkVoa2tVSnZUK2MxSE9s
            UGJSdHlOSTRaMWM0elYvSXg2NEdKeDRMSGdNCmQwQkc2MG5DR0hycWNKeGdVM3dU
            L2NJRGZvbzk1ckJDL3NwV05nelRWdU0KLS0tIDgvZlpVY2NKTlVnWTVFalZiUUcv
            aTJMZklSTnorcXpGc1FpU1ZJTGlpRXcKl8eN8cMkTA3/9VydVlb1BBv8RIdyXu4C
            7zLqPm/JcTUlnkASAMF97lOJh2WqZD/Mz2jqNP/Snr99lepkGz2lzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ayd37q6cyqrh2d2jgz04jx0guxmj483d0tchhqd6sd83ukcf4vusm4p63q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T09:22:32Z"
    mac: ENC[AES256_GCM,data:whlyrb/gVh74omm8qKwjkHY/tBX3K8Ejp+S8CWzwxPBcP8OM0xXnp3MjXKDhIO7YnuibP3s0zM33U53vQ1wwr9orrhI+pSL6BSBJrZ8Lr2MweTvSsn7XBL2qj2WHj+cgas0ALDuwcMWe65HkeTJt8hj0M2s08ScRsTw8kQLGtuA=,iv:YhqxXiRYLElEM1msXYvtdBY97jciGmQAkEdpHWeO8vo=,tag:QWsTCaHeDs3CeK0xzaxMPw==,type:str]
    version: 3.13.1
