apiVersion: v1
kind: Secret
metadata:
    name: anylink-secret
    namespace: vpn
type: Opaque
stringData:
    LINK_JWT_SECRET: ENC[AES256_GCM,data:TAaOz4/8ERHs0W1BV66pV1URbxD4VdggoiRgjqKYTUnbP+HkOqo+mnBnwLI=,iv:PhkUAwMef77xwQhXnY3yoIiRIesJmyGpsDt/oRcymaM=,tag:IBmXIjHxdaAovLXW5RGOIw==,type:str]
    #ENC[AES256_GCM,data:AOLc5GlwFlmf0Fv2z3E+sH6FHtr35/Kjmcjd5YB1uV3hShJReI0/EzT3roRvjThHF5w+f0OYTmk5vY9zQg==,iv:7b8O0vtMS6AoygIg04VKxMZ699WzSlKw2lUIFycrQbs=,tag:0fSFtK4nWPtvE3HtFigy0w==,type:comment]
    #ENC[AES256_GCM,data:mEstumHffQSpEeMdk8gn4bI0z7gHNz4oyq78Ea7c9cN8CI2lhnfFjKYmFzh6cjSFOz+xApd91rW0Fp8zntWZuyXnMDyJ0PwR2A==,iv:CW5s6YH3akuzdInujPe6PLcxlnKpOH8CxYWsCZ4Ljyg=,tag:tGnnenZ4/5/KEnHD1fJQqA==,type:comment]
    #ENC[AES256_GCM,data:aNGoEFAx5Tn4NFQ8uHsfFEmxZSxtHgKwxsTjcoA/Thj3SJvwY0alJHRRwOKDdA==,iv:ojKWyJ2nh7VzbjZMjlGlXs1v07bJieKBMIuGRj0yj5g=,tag:JDqUktwVl/TQDqYTOEFa4Q==,type:comment]
    LINK_ADMIN_PASS: ENC[AES256_GCM,data:M7RRkgWdQkRimlN6winaIQGnhBegEsiYpGxfINM2/1j9BRHHSd8ss945WVx5ZMXV9BfAMy2sefoeB93B,iv:1s5bBMuf7eYg1mUdNtYtH/J4Q8J+6Blx7AnS/s3FGBo=,tag:bmL1+C+7Xqa19pNEbX7HZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZGpuVGhSQ0RSRmo0Vllk
            RHZ4aVBCSnJ2SzVMY1g4UFlJMGoxODE5WERFCi91eHVZVjFKL0xnL0hpQnhOWXIv
            VHZ0Y3B2bThWYXg5RStvV3ZZNW81MVUKLS0tIGVlL2NwRHRoeXVpS3RtZVdCWXFU
            RWp3VUZNWE5pN2ZjTlVKSzFLd2VuK00KEgAkJ7xw7hE1SuLXGIYqwdg/AMvPUJH6
            8AxcJcXEHrDfJKs8IPqRohPTWFinuNAppB+IHw/aNQMzDGvwA45fMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ayd37q6cyqrh2d2jgz04jx0guxmj483d0tchhqd6sd83ukcf4vusm4p63q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T10:16:35Z"
    mac: ENC[AES256_GCM,data:ljvjSx8cTskSf6Kce4OFXu7JKzS0oP5Bx7BnKiSkp/pyK/XCruKdabiKe90N8zHZNFWx08r/zI0javxapLP78OCtFviFpQ/YZV65444sZYhTthFTm9+rGx1vu2rPd35U7KqbStIqN45KRvwW6ViVkuxmXYsrGzKKHu4V1St8s/0=,iv:j0kv1sGwDRP0oPNk7Jsan5ncRcMXXMd9WObLpqgJnys=,tag:B94/pleynSmqHBwJVBtfSg==,type:str]
    version: 3.13.1
