apiVersion: v1
kind: Secret
metadata:
    name: gost-config
    namespace: vpn
type: Opaque
stringData:
    gost.yml: ENC[AES256_GCM,data:17Us6GsD1tCwT93Sr+sZP/x1y/Dr2nvfgTCLHKG/TuQ6tdWs5hE+sL9pE9KLruEFtPMfpaHREDEK8FzeZ2e09cp1Bep7FV1XCSxq4+crNmUpY8fYjnPuRG7fcRUZEcRJYz2xg5q6bg+qNeypHtPgQjhTH9iwhTUy7aWHngtdR/fXLfXsUcsz/psH9xFWnwGJsRUzfhn35IM3IDO/GQAMiL/h+D8oK4sd1vecNd9Y0hX0CVRxon9TdYhuPn9V3QD/SSZWE2AFJmTizzIdgahSjgxUu/7BJsKmzyKl1ikTUTs9SUMpRuzijcoAO9MzlXMR24BroIuTwcK+QAfKqRQmvJtE/ggsbuq4jSYpIMDVaIW8wqJmTcTzefh6CJzZeDLPeumEZstGbuE/3ODcB5jvjMbVjF3VI9cTP+Od//F3cfq/m2CJc9bmdlL+BX4cojc4FEKQZOZiSPZu6kKu5VJ6XrX6biHk64pBXNjIEOmZQCsYrp8dWETWDybQT0ctrh5YoiJebOLU8FXRsF1D45Y8pk1kwlxA8UDZ60bH7CZyS8HDVmvO3jxJyIKeyo2Pu2prNA4x0GC2sxU9ETHgBy1RN3LDjOGENrkd7rF51XwBLDB/Ho0TpUOGrOhzoM++4atVRer10OrnkdBWgZBM+NpffLB921Pe9/onqh4a5A==,iv:TAwTlQI9/DoayTzfFytUsUlxVP+onT2KHtYtMrOwJ9I=,tag:KLdwXCK1WyFJ9yxQxCEgfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWGEzc3RyY1BESVdUWUJr
            MHNIVHpSZjVNZ3BUc3dJUFJnQ0ZqQjlQWlJBCldiN0dCYmlSck1KbHVzYXNsd0V1
            NWZsTjdoWFllZUV0dzA4V0pjMmxmN2cKLS0tIFpsbkNHZVlISjhkUzZYQ25iOVpV
            cnlTUDdCUHpHczN2RjJjZ0NJKzBWaFUKjZHMoD7ObTZ9wLDaCqGIZ8QbYu7b6CKp
            OIWAQhr98bxO5WSWHwrJsLEsXmXWvB77FgGSvaewctxgD0shDkD/yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ayd37q6cyqrh2d2jgz04jx0guxmj483d0tchhqd6sd83ukcf4vusm4p63q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T04:01:33Z"
    mac: ENC[AES256_GCM,data:vLXdGDvynJo+ZWojH7Um/qV3M5iXQ2c7kF4VwWOu06T7WMtoscoKias0ahC1YxcX6M7/T1C3BoHCkJzIh7ozakQ90C+4nuqeiImSnRKjsW/aYzEJ18RND018IZatY1x4c1SQKN8bQasTTe9T0F+/onWEuJytrlfMz7WS/w0D614=,iv:PySlOC/YlGD/sK3kjPxipi/hq9GmXdLCbtY3GrnwzwI=,tag:wNWfgPEq2aT1rycYlLGWvA==,type:str]
    version: 3.13.1
